name: suggestion_text_field
description: Text field that provides a pop-up with suggestions.
version: 0.3.0+1
homepage:

environment:
    sdk: ">=2.12.0 <3.0.0"
    flutter: ">=1.17.0"

dependencies:
    provider: ^6.0.0
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter
flutter:
